/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru.server

import com.fasterxml.jackson.databind.SerializationFeature
import io.ktor.client.*
import io.ktor.client.engine.cio.*
import io.ktor.client.features.json.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import ru.fly.data.Webhook
import java.text.DateFormat

suspend fun main() {
    val appId: String = System.getenv()["APP_ID"].toString()
    val webhookToken: String = System.getenv()["WEBHOOK_TOKEN"].toString()

    val webHook = Webhook(appId = appId, token = webhookToken);

    println(webHook)

    val client = HttpClient(CIO) {
        install(JsonFeature) {
            serializer = JacksonSerializer() {
                enable(SerializationFeature.INDENT_OUTPUT)
                dateFormat = DateFormat.getDateInstance()
            }
        }
    }
    val response: HttpResponse = client.get("https://discordapp.com/api/webhooks/$appId/$webhookToken")
    println(response.status)
}
