/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru.server

import com.fasterxml.jackson.databind.SerializationFeature
import io.ktor.client.*
import io.ktor.client.engine.cio.*
import io.ktor.client.features.json.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import ru.fly.data.Webhook
import ru.fly.data.WebhookContent
import java.text.DateFormat

suspend fun main() {
    val appId: String = System.getenv()["APP_ID"].toString()
    val webhookToken: String = System.getenv()["WEBHOOK_TOKEN"].toString()

    val webHook = Webhook(appId = appId, token = webhookToken)
    val webhookContent: WebhookContent = WebhookContent("Some text, just for fun, for now, lol.")

    webHook.content = webhookContent

    val client = HttpClient(CIO)

    val response: HttpResponse = client.post("https://discordapp.com/api/webhooks/$appId/$webhookToken") {
        headers {
            append(HttpHeaders.Accept, "application/json")
            append(HttpHeaders.ContentType, "application/json")
        }

        contentType(ContentType.Application.Json)
        body = webHook.json()
    }
    println(response.status)
}
