/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru.elerphore

import io.ktor.client.*
import io.ktor.client.engine.cio.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import ru.elerphore.DiscordClient

suspend fun main() {
    println(System.getenv().get("WEBHOOK_TOKEN"))
    println(System.getenv().get("APP_ID"))

    val client = HttpClient(CIO)
    val response: HttpResponse = client.get("https://google.com")
    println(response.status)

//    DiscordClient().testing()
}
